# Generated by Django 3.2.4 on 2021-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('BR', 'Завтрак'), ('LU', 'Полдник'), ('DI', 'Обед'), ('SU', 'Ужин'), ('SN', 'Закуска')], default='BR', max_length=7)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
